---
title: "03 - Simple Regression Model"
author: "Murray"
date: "5/9/2020"
output: html_document
---

GLM Predicts deaths x days after initial outbreak given average age, GDP (PPP), and Obesity rate


```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

simple_model_data
```

```{r}
simple_model_data_with_start <- simple_model_data_with_start

model_variables <- simple_model_data %>%
  group_by(Country, Obesity_rate, gdp_estimate_ppp, Median_Age, population_size, peak_deaths_already_occurred_indicator, fatality_rate) %>%
  summarise(deaths_per_million = max(total_deaths_per_million),
            smooth_deaths_per_million = max(deaths_5_day_averages)) %>%
  filter(!is.na(Obesity_rate) & !is.na(gdp_estimate_ppp) & !is.na(Median_Age) & !is.na(deaths_per_million) & !is.na(fatality_rate) &
           peak_deaths_already_occurred_indicator == 1 &
           population_size > 3 &
           deaths_per_million > 0
         )


ggplot(data = model_variables, aes(x = Obesity_rate)) +
  geom_density()

ggplot(data = model_variables, aes(x = Median_Age)) +
  geom_density()

ggplot(data = model_variables, aes(x = fatality_rate)) +
  geom_density()

ggplot(data = model_variables, aes(x = gdp_estimate_ppp)) +
  geom_density()

exp(model_variables$gdp_estimate_ppp)

ggplot(data = model_variables, aes(x = ((gdp_estimate_ppp - mean(gdp_estimate_ppp))/ sd(gdp_estimate_ppp)))) +
  geom_density()
  
```

```{r}
ggplot(data = model_variables, aes(x = gdp_estimate_ppp, y = deaths_per_million)) +
  geom_line()

ggplot(data = model_variables, aes(x = Median_Age, y = deaths_per_million)) +
  geom_line()

ggplot(data = model_variables, aes(x = Obesity_rate, y = deaths_per_million)) +
  geom_line()
```

```{r}
m3 <- lm(data = model_variables, formula = deaths_per_million ~ Obesity_rate + Median_Age + log(gdp_estimate_ppp))

a1 <- anova(m3)

summary(m3)
```

```{r}
m1 <- glm(data = model_variables, formula = deaths_per_million ~ Obesity_rate + Median_Age + log(gdp_estimate_ppp))

a1 <- anova(m1)

summary(m1)
```

```{r}
m2 <- glm(data = model_variables %>% filter(deaths_per_million > 0), family = Gamma("log"), formula = deaths_per_million ~ Obesity_rate + fatality_rate + log(gdp_estimate_ppp))

summary(m2)
```
```{r}
4.7122 - 2 * 1.0919
```


```{r}
m4 <- glm(data = model_variables %>% filter(deaths_per_million > 0), family = Gamma("log"), formula = deaths_per_million ~ Obesity_rate + fatality_rate + log(gdp_estimate_ppp) + fatality_rate * Obesity_rate)

summary(m4)
```

```{r}
m5 <- glm(data = model_variables %>% filter(deaths_per_million > 0), family = Gamma("log"), formula = deaths_per_million ~ Obesity_rate + fatality_rate + log(gdp_estimate_ppp) + fatality_rate * log(gdp_estimate_ppp))

summary(m5)
```

```{r}
m6 <- glm(data = model_variables %>% filter(deaths_per_million > 0), family = Gamma("log"), formula = deaths_per_million ~ Obesity_rate + Median_Age + log(gdp_estimate_ppp) + log(gdp_estimate_ppp) * Obesity_rate)

summary(m6)
```

```{r}
m7 <- glm(data = model_variables %>% filter(deaths_per_million > 0), family = Gamma("log"), formula = deaths_per_million ~ Median_Age * log(gdp_estimate_ppp))

summary(m7)
```


```{r}
ggplot(data = NULL, aes(x = m2$fitted.values, y = model_variables$deaths_per_million)) + 
  geom_point()
```

```{r}
ggplot(data = model_variables %>% filter(deaths_per_million > 0), aes(x = m2$fitted.values, y = deaths_per_million)) + 
  geom_point()
```


```{r}
plot(m2)
```



